version: '3.3'

services:
  web:
    restart: always
    build: ./web
    depends_on:
      - postgres
      - redis
      - caddy
    expose:
      - 8000
    volumes:
      - ./web:/usr/src/app
    env_file: .env
    environment:
      DEBUG: 'true'
    command: python manage.py runserver 0.0.0.0:8000

  caddy:
    restart: always
    image: abiosoft/caddy
    environment:
      ACME_AGREE: "true"
    ports:
      - 80:80
    volumes:
      - ./web:/srv
      - ./caddy/Caddyfile:/etc/Caddyfile
      - ./caddy:/root/.caddy
      - ./caddy:/var/log

  postgres:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    restart: always
    image: redis:latest
    ports:
      - 6379
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata: